[package]
name = "egui-winit-ash-integration"
version = "0.6.0"
authors = ["Orito Itsuki <orito.itsuki@gmail.com>"]
description = "This is the egui integration crate for winit and ash."
edition = "2021"
homepage = "https://docs.rs/egui-winit-ash-integration"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/egui-winit-ash-integration"
readme = "README.md"
repository = "https://github.com/MatchaChoco010/egui-winit-ash-integration"
categories = ["gui", "game-development"]
keywords = ["gui", "winit", "ash", "vulkan", "gpu-allocator"]
include = [
  "src/*.rs",
  "src/shaders/spv/*.spv",
  "Cargo.toml",
]

[features]
default = [ "gpu-allocator-feature", "egui-winit/default" ]
gpu-allocator-feature = [ "gpu-allocator" ]

## Underlying egui-winit features
accesskit = ["egui-winit/accesskit"]
android-game-activity = ["egui-winit/android-game-activity"]
android-native-activity = ["egui-winit/android-native-activity"]
bytemuck = ["egui-winit/bytemuck"]
clipboard = ["egui-winit/clipboard"]
links = ["egui-winit/links"]
serde = ["egui-winit/serde"]
wayland = ["egui-winit/wayland"]
x11 = ["egui-winit/x11"]


[dependencies]
anyhow = "1.0.98"
ash = { version="0.38", default-features = false }
bytemuck = "1.22.0"
egui = "0.31.1"
egui-winit = { version = "0.31.1", default-features = false }
gpu-allocator = { version = "0.27", optional = true }
raw-window-handle = { version="0.6.2" }

[dev-dependencies]
ash-window = "0.13.0"
crevice = "0.18.0"
image = "0.25.6"
memoffset = "0.9.1"
mint = "0.5.9"
tobj = "4.0.3"
ash = { version="0.38", default-features = false, features = ["linked", "debug"] }

[dev-dependencies.cgmath]
version = "0.18.0"
features = ["mint"]
